### ISSUE TITLE
--header issues

### ISSUE THREAD

**Issue by AcarBurak** [dov/paps#30] opened 2019-10-25 02:33 UTC
Thank you for the very useful programme.

Ability to configure the header would help a lot, that is, unless you yourself choose to remove the date and the "Page" strings.

The "Page" string ruins a non-English conversion and don't you think it's redundant in the first place?

The date string ruins any conversion.

![header](https://user-images.githubusercontent.com/47071810/67538751-b6216c00-f6e8-11e9-8d76-a23dfc490aa7.jpg)

**Comment by gnusupport** [comment] 2022-12-17 09:25
I have the same problem, I would like to configure header.

**Comment by dov** [comment] 2022-12-17 21:37
Thanks for asking about this! So I made a first implementation of it, and pushed it as part of the forthcoming version 0.8. As part of the implementation I switched to C++17. I hope it doesn't annoy to many people. 

I have added three new command line options to paps:

* `--header-left` - The left side of the header
* `--header-center` - The center of the header
* `--header-left` - The right side of the header

They all take a string that is based on python f-strings. I have defined the following variable that may be used in the definitions of the headers:

* `path` - The complete path of the file being printed
* `filename` - The basename (without directory) of the file being printed
* `mtime` - The file's modification time
* `now` - The current time
* `num_pages` - The total number of pages in the document
* `page_idx` - The current page being printed

Here is an example of how it may be used:

```
paps --header-left="{now:%Y-%m-%d %H:%M}" --header-center="{filename}" --header-right="Page {page_idx:02d}/{num_pages:02d}" --header -o hello.pdf paps.cc
```

Please let me know your feedback.

**Comment by dov** [comment] 2022-12-17 21:44
Since this is a duplicate of #4 , I'll close this issue.

**Closed by dov** 2022-12-17 21:44 UTC

**Comment by gnusupport** [comment] 2022-12-18 00:37
That is great. I use `paps´  to make nice PDF printouts from Emacs buffers. It is very useful for reporting purposes. 

I guess you have forgot to customize analogously the `--footer´ option.

Just that I cannot build it, neither `configure´ nor `meson´ works, you may see it in my other comment.

**Comment by dov** [comment] 2022-12-27 18:30
> That is great. I use `paps` to make nice PDF printouts from Emacs buffers. It is very useful for reporting purposes.
> 
> I guess you have forgot to customize analogously the `--footer` option.
> 
> Just that I cannot build it, neither `configure` nor `meson` works, you may see it in my other comment.

Note that I added footer as well, and fixed the compilation (I think). Did you have a chance to test it?

**Comment by gnusupport** [comment] 2022-12-28 09:21
That is more than great, in the next step I will test it and make Emacs Lisp package for Emacs buffer printing and previews.

**Comment by gnusupport** [comment] 2022-12-30 17:17
For me it works very nice and very well.

GNU Emacs package: rcd-paps.el: +
https://gnu.support/gnu-emacs/packages/GNU-Emacs-package-rcd-paps-el-76862.html
